# Crie um programa que leia um numero e mostre na tela a sua tabuada
nu = int(input('Digite um numero para ver sua tabuada: '))
print('\033[35;40m''-x-' '\033[m'*4)
print('{} x {:2} = {}'.format(nu, 1, nu*1))
print('{} x {:2} = {}'.format(nu, 2, nu*2))
print('{} x {:2} = {}'.format(nu, 3, nu*3))
print('{} x {:2} = {}'.format(nu, 4, nu*4))
print('{} x {:2} = {}'.format(nu, 5, nu*5))
print('{} x {:2} = {}'.format(nu, 6, nu*6))
print('{} x {:2} = {}'.format(nu, 7, nu*7))
print('{} x {:2} = {}'.format(nu, 8, nu*8))
print('{} x {:2} = {}'.format(nu, 9, nu*9))
print('{} x {:2} = {}'.format(nu, 10, nu*10))
print('\033[35;40m''-x-' '\033[m'*4)